[project]
name = "conversableagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag2[openai]>=0.8.2",
    "jupyter>=1.1.1",
]
